#!/bin/bash
#
# WordPress plugin distribution differencing
#
# Quickly review a diff of two published versions of a WordPress plugin
# in the public WP plugin directory
#
#  Copyright (C) 2020 Peter Upfold.
# * This file is licensed to you under the Apache License, version 2.0 (the "License").
# *
# * You may not use this file except in compliance with the License. You may obtain
# * a copy of the License at
# * http://www.apache.org/licenses/LICENSE-2.0
#
# * Unless required by applicable law or agreed to in writing, software distributed under
# * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# * KIND, either express or implied. See the License for the specific language governing
# * permissions and limitations under the License.

SCRIPTNAME=wp-plugin-dist-diff  # not using $0 in case that reveals directory path information

usage() {
    echo "usage: $0 plugin-slug old-version new-version"
    echo "    e.g. $0 redirection 4.7 4.8"
}

failure() {
    >&2 echo $1
}
check_zip() {
    if [ `hexdump $1 | head -n 1 | awk '{print $2 $3}'` != '504b' ]; then
        failure "$1 is not a zip file"
        #cleanup
        exit 255
    fi
}
cleanup() {
    rm -rf $TEMPDIR
}

if (( $# != 3 )); then
    usage
    exit 1
fi

TEMPDIR=/tmp/$SCRIPTNAME-$$
ORIG=$TEMPDIR/$2.zip
NEW=$TEMPDIR/$3.zip
mkdir -p $TEMPDIR

curl -s --fail-early "https://downloads.wordpress.org/plugin/$1.$2.zip" -o $ORIG -A "$SCRIPTNAME"
exitcode=$?

if [ $exitcode -ne 0 ]; then
    failure "Failed to download $1 $2 with exit code $exitcode"
    exit $exitcode
fi

curl -s --fail-early "https://downloads.wordpress.org/plugin/$1.$3.zip" -o $NEW -A "$SCRIPTNAME"
exitcode=$?
if [ $exitcode -ne 0 ]; then
    failure "Failed to download $1 $3 with exit code $exitcode"
    exit $exitcode
fi

# check filetypes
check_zip $ORIG
check_zip $NEW

mkdir $TEMPDIR/$2
mkdir $TEMPDIR/$3

unzip -qq $ORIG -d $TEMPDIR/$2
unzip -qq $NEW -d $TEMPDIR/$3

git diff $TEMPDIR/$2 $TEMPDIR/$3

cleanup